version: '3.1'
services:
  casdoor:
    restart: always
    image: casbin/casdoor
    entrypoint: /bin/sh -c './server'
    ports:
      - "8000:8000"
    environment:
      RUNNING_IN_DOCKER: "true"
    user: root
    volumes:
      - ./conf:/conf  # Maps ./conf on the host to /conf in the container
